---
listening_port: 4002
prometheus_port: 4004
minimum_log_level: 'debug'

middlewares:
  - type: add_response_header
    name: 'WWW-Authenticate'
    value: 'Basic realm="GitLab Packages Registry"'
    when:
      status_code_is: 401
  - type: block_request
    status_code: 401
    when:
      header_exists: 'authorization'
  - type: block_request
    status_code: 404
    when:
      any:
        - path_contains: '*metadata/microsoft.*'
        - path_contains: '*metadata/system.*'
        - path_contains: '*metadata/grpc.*'
        - path_contains: '*metadata/xunit.*'
  - type: add_response_header
    name: 'X-Cache-Status'
    value: '$cache_status'
  - type: use_cache
    cache_name: 'metadata'
    when:
      path_contains: '*/packages/nuget/metadata/*'
  - type: use_cache
    cache_name: 'packages'
    when:
      path_contains: '*/packages/nuget/download/*'
  - type: replace_response_body
    find: 'https://gitlab.com'
    replacement: 'http://nuget-cache.prod-euw1.euw1.eqtv.io'
    when:
      path_contains: '*/index.json'
  - type: forward_request
    target_host: 'www.nuget.org'

caches:
  - in_memory:
      name: 'packages'
      ttl_seconds: 86400
      hash_path: true
      hash_query: true
      hash_body: false
  - in_memory:
      name: 'metadata'
      ttl_seconds: 90
      hash_path: true
      hash_query: true
      hash_body: false
